/* This file is auto-generated by InSpatial ORM. Do not edit manually. */

import type {
  ChildList,
  EntryBase,
  SettingsBase,
} from "@inspatial/cloud/types";

declare module "@inspatial/cloud/models" {
  export interface EntryMap {
  }

  export interface SettingsMap {
  }
}
